#####  03- 巨量資料分析與應用 Using - R - 資料整理篇02  ####

# https://cran.r-project.org/web/packages/dplyr/dplyr.pdf

### Introducing DPLYR TUTORIAL (WITH 50 EXAMPLES) -----
## Introducing Time Series Analysis with dplyr
# Important dplyr Functions to remember
# 
# dplyr 函數  | 用途                           |  Equivalent SQL
# ------------| --------------------------     | ----------------
# select()	  | Selecting columns (variables)  | SELECT
#               選擇欄位（變量）
# filter()	  | Filter (subset) rows.	       | WHERE
#               過濾（子集）橫列(觀測值)。
# group_by()  | Group the data	               | GROUP BY
#               分組數據
# summarise() | Summarise (or aggregate) data  | -
#               總結（或匯總）數據
# arrange()	  | Sort the data	               | ORDER BY
#               對數據進行排序
# join()	  | Joining data frames (tables)   | JOIN
#               連結資料集（表格）
# mutate()	  | Creating New Variables	       | COLUMN ALIAS
#               創建新變量
# 
# ## Data : Income Data by States
# * DPLYR TUTORIAL (WITH 50 EXAMPLES)

# 首先先將 sampledata.csv 資料匯入 How to load Data
# https://sites.google.com/site/pocketecoworld/sampledata.csv
# url <- "https://sites.google.com/site/pocketecoworld/sampledata.csv"
# mydata = read.csv(url)


mydata = read.csv("data/sampledata.csv")
dim(mydata)  # [1] 51 16
names(mydata)
# [1] "Index" "State" "Y2002" "Y2003" "Y2004" "Y2005" "Y2006" "Y2007" "Y2008" "Y2009" "Y2010" "Y2011"
# [13] "Y2012" "Y2013" "Y2014" "Y2015"

str(mydata)
# 'data.frame':	51 obs. of  16 variables:
# $ Index: Factor w/ 19 levels "A","C","D","F",..: 1 1 1 1 2 2 2 3 3 4 ...
# $ State: Factor w/ 51 levels "Alabama","Alaska",..: 1 2 3 4 5 6 7 8 9 10 ...
# $ Y2002: int  1296530 1170302 1742027 1485531 1685349 1343824 1610512 1330403 1111437 1964626 ...
# $ Y2003: int  1317711 1960378 1968140 1994927 1675807 1878473 1232844 1268673 1993741 1468852 ...
# $ Y2004: int  1118631 1818085 1377583 1119299 1889570 1886149 1181949 1706751 1374643 1419738 ...
# $ Y2005: int  1492583 1447852 1782199 1947979 1480280 1236697 1518933 1403759 1827949 1362787 ...
# $ Y2006: int  1107408 1861639 1102568 1669191 1735069 1871471 1841266 1441351 1803852 1339608 ...
# $ Y2007: int  1440134 1465841 1109382 1801213 1812546 1814218 1976976 1300836 1595981 1278550 ...
# $ Y2008: int  1945229 1551826 1752886 1188104 1487315 1875146 1764457 1762096 1193245 1756185 ...
# $ Y2009: int  1944173 1436541 1554330 1628980 1663809 1752387 1972730 1553585 1739748 1818438 ...
# $ Y2010: int  1237582 1629616 1300521 1669295 1624509 1913275 1968730 1370984 1707823 1198403 ...
# $ Y2011: int  1440756 1230866 1130709 1928238 1639670 1665877 1945524 1318669 1353449 1497051 ...
# $ Y2012: int  1186741 1512804 1907284 1216675 1921845 1491604 1228529 1984027 1979708 1131928 ...
# $ Y2013: int  1852841 1985302 1363279 1591896 1156536 1178355 1582249 1671279 1912654 1107448 ...
# $ Y2014: int  1558906 1580394 1525866 1360959 1388461 1383978 1503156 1803169 1782169 1407784 ...
# $ Y2015: int  1916661 1979143 1647724 1329341 1644607 1330736 1718072 1627508 1410183 1170389 ...
summary(mydata)

View(mydata)

# * 在本教程中，我們使用以下數據，其中包含從2002年至2015年各州生成的收入。
# * 注意：此數據不包含州的實際收入數字。
# * 該數據集包含51個觀察值（行）和16個變量（列）。 
# * 數據集的幾行和列的快照如下所示。
# * In this tutorial, we are using the following data which contains 
#   income generated by states from year 2002 to 2015. 
# * Note : This data do not contain actual income figures of the states.
# * This dataset contains 51 observations (rows) and 16 variables (columns). 
# * The snapshot of few rows and columns of the dataset is shown below.
install.packages("dplyr")
library(dplyr) 

## Example 1 : 選擇隨機 N 行 Selecting Random N Rows ------------
# * The sample_n function selects random rows from a data frame (or table). 
# * The second parameter of the function tells R the number of rows to select.
# * sample_n函數從數據框（或表）中選擇隨機行。
# * 函數的第二個參數告訴R要選擇的行數。
# *

?sample
# * sample {dplyr}  ---  Sample n rows from a table

# * sample_n(tbl, size, replace = FALSE, weight = NULL, .env = NULL)
# * sample_frac(tbl, size = 1, replace = FALSE, weight = NULL, .env = NULL)

sample_n(mydata, 3)
sample_n(mydata, 20)
sample_n(mydata, 20, replace = TRUE)

## 反思01: 請問這指令有何用途????   日後抽樣或訓練集與測試集

### Example 2 : Selecting Random Fraction(分數或比例) of Rows -----
# * The sample_frac function returns randomly N% of rows. 
# * In the example below, it returns randomly 10% of rows.

sample_frac(mydata, 0.1)

##  比例對嗎?
length(sample_frac(mydata, 0.1))
nrow(sample_frac(mydata, 0.1))
nrow(sample_frac(mydata, 0.1))/nrow(mydata)

## 原廠 sample {dplyr} 範例：
#Examples
data(mtcars)
dim(mtcars)  # [1] 32 11

# Sample fixed number per group
sample_n(mtcars, 10)
sample_n(mtcars, 50, replace = TRUE)
sample_n(mtcars, 10, weight = mpg)

sample_n(by_cyl, 3)
sample_n(by_cyl, 10, replace = TRUE)
sample_n(by_cyl, 3, weight = mpg / mean(mpg))

# Sample fixed fraction per group
# Default is to sample all data = randomly resample rows
sample_frac(mtcars)

sample_frac(mtcars, 0.1)
sample_frac(mtcars, 1.5, replace = TRUE)
sample_frac(mtcars, 0.1, weight = 1 / mpg)

sample_frac(by_cyl, 0.2)
sample_frac(by_cyl, 1, replace = TRUE)
# end of Examples

## 反思02: 請問這二指令sample_n, sample_frac 哪一個較常用????   日後抽樣或訓練集與測試集

## Example 3 : 基於所有變量刪除重複行（完整行）Remove Duplicate Rows based on all the variables (Complete Row) -----
# * The distinct function is used to eliminate duplicates.
# ```{r Example 3 : Remove Duplicate Rows based on all the variables (Complete Row)}
?distinct  # Select distinct/unique rows
           # Retain only unique/distinct rows from an input tbl. 
           # This is similar to unique.data.frame(), but considerably faster.

mydata[51, ]
mydata52 <- rbind(mydata,mydata[51, ] )
identical(mydata, mydata52)

mydataDistinct <- distinct(mydata52)
identical(mydata, mydataDistinct)

?identical   # Test Objects for Exact Equality

## 反思03: 請問這指令distinct 用途???? 

## Example 4 : 根據欄位(變量)刪除重複行 Remove Duplicate Rows based on a variable ------
# * The .keep_all function is used to retain all other variables in the output data frame.
# ```{r Example 4 : Remove Duplicate Rows based on a variable}

(x2 = distinct(mydata, Index, .keep_all= TRUE))
#    Index          State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009
# 1      A        Alabama 1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173
# 2      C     California 1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809
# 3      D       Delaware 1330403 1268673 1706751 1403759 1441351 1300836 1762096 1553585

(IndexNo = distinct(mydata, Index, .keep_all= FALSE))
#    Index
# 1      A
# 2      C
# 3      D
# 4      F

# R 類似語法
unique(mydata$Index)
# [1] A C D F G H I K L M N O P R S T U V W
# Levels: A C D F G H I K L M N O P R S T U V W

## 反思04: 請問這指令distinct 根據欄位(變量)刪除重複行用途???? 

## Example 5 : 基於多個欄位(變量)刪除重複行 Remove Duplicates Rows based on multiple variables ------
# * In the example below, we are using two variables - Index, Y2010 to determine uniqueness.
# 
# ```{r Example 5 : Remove Duplicates Rows based on multiple variables}
(x3 = distinct(mydata, Index, Y2010, .keep_all= TRUE))
(x4 = distinct(mydata, Index, Y2010, .keep_all= FALSE))

## 原廠 distinct {dplyr}	R Documentation 範例：
# * Select distinct/unique rows
# * Retain only unique/distinct rows from an input tbl. 
# * This is similar to unique.data.frame(), but considerably faster.
# * 選擇不同/唯一的列 rows
# * 從輸入tbl只保留唯一/不同的列。
# * 這與unique.data.frame（）類似，但是要快得多。
# * 
#     * distinct(.data, ..., .keep_all = FALSE)
# 
# ```{r 原廠 distinct {dplyr}	R Documentation 範例：}
# Examples

df <- tibble(
    x = sample(10, 100, rep = TRUE),
    y = sample(10, 100, rep = TRUE)
)
nrow(df)
nrow(distinct(df))
nrow(distinct(df, x, y))

distinct(df, x)
distinct(df, y)

# Can choose to keep all other variables as well
distinct(df, x, .keep_all = TRUE)
distinct(df, y, .keep_all = TRUE)

# 您也可以使用不同的計算變量 You can also use distinct on computed variables
distinct(df, diff = abs(x - y))

# The same behaviour applies for grouped data frames
# except that the grouping variables are always included
df <- tibble(
    g = c(1, 1, 2, 2),
    x = c(1, 1, 2, 1)
) %>% group_by(g)
df %>% distinct()
df %>% distinct(x)


#1. select( ) Function 選擇變量（或欄位）
# * It is used to select only desired variables.
# * select() syntax : select(data , ....)
# * data : Data Frame
# * .... : Variables by name or by function 

## Example 6 : 選擇變量（或欄位） Selecting Variables (or Columns) ------------
# * Suppose you are asked to select only a few variables. 
# * The code below selects variables "Index", columns from "State" to "Y2008".
# * 假設您被要求僅選擇幾個變量。
# * 下面的代碼從“狀態”到“Y2008”的列中選擇變量“Index”。
names(mydata)
# ```{r Example 6 : Selecting Variables (or Columns)}
(mydata2 = select(mydata, Index, State:Y2008))

(mydata2a = select(mydata, Index, c(State,Y2008)))
(mydata2b = select(mydata, Index, c(State,Y2008, Y2012:Y2015)))
(mydata2c = select(mydata, -Index))
(mydata2d = select(mydata, -Index, -c(State,Y2008)))

## Example 7 : 刪除變量 Dropping Variables --------------
# * The minus sign before a variable tells R to drop the variable.
# 
# ```{r Example 7 : Dropping Variables}
dim(mydata)
mydataDrop = select(mydata, -Index, -State)
dim(mydataDrop)
# The above code can also be written like :
mydataDrop2 = select(mydata, -c(Index,State))
dim(mydataDrop2)


## Example 8 : 選擇或刪除變量以'Y'開始 Selecting or Dropping Variables starts with 'Y' ----
# * The starts_with() function is used to select variables starts with an alphabet.
# 
# ```{r Example 8 : Selecting or Dropping Variables starts with Y}
mydata3 = select(mydata, starts_with("Y"))
dim(mydata)    # [1] 51 16
dim(mydata3)   # [1] 51 14

# Adding a negative sign before starts_with() implies dropping the variables starts with 'Y'
mydata33 = select(mydata, -starts_with("Y"))
dim(mydata33)   # [1] 51  2


## The following functions helps you to select variables based on their names.
# Helpers 函數    | Description 用途                           
# ----------------| --------------------------     
# starts_with()	  | Starts with a prefix
# ends_with()	  | Ends with a prefix
# contains()	  | Contains a literal string
# matches()	      | Matches a regular expression
# num_range()	  | Numerical range like x01, x02, x03.
# one_of()	      | Variables in character vector.
# everything()	  | All variables.

## Example 9 : Selecting Variables contain(包含) 'I' in their names ------------
# 
# ```{r Example 9 : Selecting Variables contain I in their names}
names(mydata)
mydata4 = select(mydata, contains("I"))
names(mydata4)
# [1] "Index"

mydata4 = select(mydata, contains("Y"))
names(mydata4)


## Example 10 : 重新排列變量 Reorder Variables with everything() ------------
# * The code below keeps variable 'State' in the front and the remaining variables follow that.
# * 下面的代碼保持前面的位置變量“State”，其餘的變量跟隨。
# ```{r Example 10 : Reorder Variables}

mydata5 = select(mydata, State, everything())
names(mydata)
# [1] "Index" "State" "Y2002" "Y2003" "Y2004" "Y2005" "Y2006" "Y2007" "Y2008" "Y2009" "Y2010" "Y2011"
# [13] "Y2012" "Y2013" "Y2014" "Y2015"
names(mydata5)
# [1] "State" "Index" "Y2002" "Y2003" "Y2004" "Y2005" "Y2006" "Y2007" "Y2008" "Y2009" "Y2010" "Y2011"
# [13] "Y2012" "Y2013" "Y2014" "Y2015"

mydata5a = select(mydata, State,Y2015, everything())
names(mydata5a)
# [1] "State" "Y2015" "Index" "Y2002" "Y2003" "Y2004" "Y2005" "Y2006" "Y2007" "Y2008" "Y2009" "Y2010"
# [13] "Y2011" "Y2012" "Y2013" "Y2014"

## 原廠 select {dplyr}	R Documentation 範例：
# * Select/rename variables by name
# * select() keeps only the variables you mention; rename() keeps all variables.
# * Usage
# * select(.data, ...)
# * rename(.data, ...)
# ```{r 原廠 select {dplyr}	R Documentation 範例：}
# Examples
iris <- as_tibble(iris) # so it prints a little nicer
select(iris, starts_with("Petal"))
select(iris, ends_with("Width"))

# Move Species variable to the front
select(iris, Species, everything())

df <- as.data.frame(matrix(runif(100), nrow = 10))
df <- tbl_df(df[c(3, 4, 7, 1, 9, 8, 5, 2, 6, 10)])
select(df, V4:V6)
select(df, num_range("V", 4:6))

# Drop variables with -
select(iris, -starts_with("Petal"))


# The .data pronoun is available:
select(mtcars, .data$cyl)
select(mtcars, .data$mpg : .data$disp)

# However it isn't available within calls since those are evaluated
# outside of the data context. This would fail if run:
# select(mtcars, identical(.data$cyl))


# 重命名  Renaming -----------------------------------------
# * select() keeps only the variables you specify
select(iris, petal_length = Petal.Length)

# * rename() keeps all variables
rename(iris, petal_length = Petal.Length)


## rename( ) Function
# * It is used to change variable name.
# * rename() syntax : rename(data , new_name = old_name)
# * data : Data Frame
# * new_name : New variable name you want to keep
# * old_name : Existing Variable Name

## Example 11 : 重命名 Rename Variables ----
# * The rename function can be used to rename variables.
# * In the following code, we are renaming 'Index' variable to 'Index1'.
# 
# ```{r Example 11 : Rename Variables}
mydata6 = rename(mydata, Index1=Index)
head(mydata6)

### 動腦練習01: 請將資料集 Year 年欄位由大到小。 時間: 5 分鐘

### 動腦練習02: 請將mydata 資料集新增 region 區域欄位 >> 變更為 mydata51 (因為 Index 只是字母順訊)
?state    # US State Facts and Figures

# names(mydata51)  <<<  驗證
# [1] "State"    "Region51" "Index"    "Y2002"    "Y2003"    "Y2004"    "Y2005"    "Y2006"    "Y2007"    "Y2008"   [11] "Y2009"    "Y2010"    "Y2011"    "Y2012"    "Y2013"    "Y2014"    "Y2015"

#2. filter( ) Function
# * It is used to subset data with matching logical conditions.
# * 它用於使用匹配的邏輯條件對數據進行子集。
# * filter() syntax : filter(data , ....)
# * data : Data Frame
# * .... : Logical Condition

## Example 12 : 假設你需要子集數據。 過濾橫列(觀測值)資料 Filter Rows ------
# * 假設你需要子集數據。 Suppose you need to subset data. 
# * You want to filter rows and retain only those values in which Index is equal to A.
# 
# ```{r Example 12 : Filter Rows}
(mydata7 = filter(mydata, Index == "A"))
(mydata7a = filter(mydata, Y2007 >= 1465841 ))
(mydata7b = filter(mydata, Y2007 >= mean(Y2007) ))

mean( mydata$Y2007)

## Example 13 : 多重選擇標準 Multiple Selection Criteria -----
# * The %in% operator can be used to select multiple items. 
# * In the following program, we are telling R to select rows against 'A' and 'C' in column 'Index'.
# 
# ```{r Example 13 : Multiple Selection Criteria}
(mydata77 = filter(mydata, Index %in% c("A", "C")))
(mydata77 = filter(mydata, Index %in% c("A", "C", "W")))

## Example 14 : 'AND'且 Condition in Selection Criteria ----

# *Suppose you need to apply 'AND' condition. 
# * In this case, we are picking data for 'A' and 'C' in the column 'Index' and income greater than 1.3 million in Year 2002.
# * 假設您需要應用“AND”條件。
# * 在這種情況下，我們在“Index”列中選擇“A”和“C”的數據，2002年的收入大於130萬。
# 
# ```{r Example 14 : AND Condition in Selection Criteria}
(mydata8 = filter(mydata, Index %in% c("A", "C") & Y2002 >= 1300000 ))


## Example 15 : 'OR'或 Condition in Selection Criteria  -----------

# * The 'I' denotes OR in the logical condition. It means any of the two conditions.

(mydata9 = filter(mydata, Index %in% c("A", "C") | Y2002 >= 1300000))

## Example 16 : NOT否(反轉) Condition ---------------
# * The "!" sign is used to reverse the logical condition.
# * “！” 符號用於反轉邏輯條件。

(mydata10 = filter(mydata, !Index %in% c("A", "C")))
#    Index                State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010
# 1      D             Delaware 1330403 1268673 1706751 1403759 1441351 1300836 1762096 1553585 1370984
# 2      D District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981 1193245 1739748 1707823
# 3      F              Florida 1964626 1468852 1419738 1362787 1339608 1278550 1756185 1818438 1198403
# 4      G              Georgia 1929009 1541565 1810773 1779091 1326846 1223770 1773090 1630325 1145473

## Example 17 : 包含條件 CONTAINS Condition  ----------------
# * The grepl function is used to search for pattern matching. 
# * In the following code, we are looking for records wherein column state contains 'Ar' in their name.
# * grepl函數用於搜索模式匹配。 
# * 在下面的代碼中，我們正在尋找其中列狀態在其名稱中包含“Ar”的記錄。


(mydata10 = filter(mydata, grepl("Ar", State)))
#   Index    State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010   Y2011
# 1     A  Arizona 1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521 1130709
# 2     A Arkansas 1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295 1928238
#     Y2012   Y2013   Y2014   Y2015
# 1 1907284 1363279 1525866 1647724
# 2 1216675 1591896 1360959 1329341

?grep
# grep {base}	R Documentation
# 模式匹配和替換 Pattern Matching and Replacement


# 原廠filter {dplyr}	R Documentation 範例：
# * Return rows with matching conditions
# * Use filter() find rows/cases where conditions are true. 
# * Unlike base subsetting, rows where the condition evaluates to NA are dropped.
# * 
#     * Useful filter functions
# * ==, >, >= etc
# * &, |, !, xor()
# * is.na()
# * between(), near()
# ```{r filter {dplyr}	R Documentation}
#Examples
?starwars   # Starwars characters 星球大戰角色
starwars

(filter(starwars, species == "Human"))
(filter(starwars, mass > 1000))

# Multiple criteria
(filter(starwars, hair_color == "none" & eye_color == "black"))
(filter(starwars, hair_color == "none" | eye_color == "black"))

# summarise( ) Function
# * It is used to summarize data.
# * summarise() syntax : summarise(data , ....)
# * data : Data Frame
# * ..... : Summary Functions such as mean, median etc

## Example 18 : 總結選定的變量 Summarize selected variables  -----
# * In the example below, we are calculating mean and median for the variable Y2015.
# * 在下面的例子中，我們計算變量Y2015的平均值和中位數。


summarise(mydata, Y2015_mean = mean(Y2015), Y2015_med=median(Y2015))
#   Y2015_mean Y2015_med
# 1    1588297   1627508

## Example 19 : 總結多個變量 Summarize Multiple Variables >> summarise_at
# * In the following example, we are calculating number of records, mean and median for variables Y2005 and Y2006. 
# * The summarise_at function allows us to select multiple variables by their names.
# * 在下面的例子中，我們計算變量Y2005和Y2006的記錄數，平均值和中位數。
# * summarise_at函數允許我們按名稱選擇多個變量。


summarise_at(mydata, vars(Y2005, Y2006), funs(n(), mean, median))
#   Y2005_n Y2006_n Y2005_mean Y2006_mean Y2005_median Y2006_median
# 1      51      51    1522064    1530969      1480280      1531641

?summarise_at
# summarise_at(.tbl, .vars, .funs, ..., .cols = NULL)


# Example 20 : 用自定義函數進行總結 Summarize with Custom Functions --------------
# * We can also use custom functions in the summarise function. 
# * In this case, we are computing the number of records, number of missing values, mean and median for * variables Y2011 and Y2012. 
# * The dot (.) denotes each variables specified in the second argument of the function.
# * 我們也可以在summary功能中使用自定義函數。
# * 在這種情況下，我們正在計算* Y2011和Y2012的記錄數量，缺失值的數量，平均值和中位數。
# * 點（。）表示函數第二個參數中指定的每個變量。

summarise_at(mydata, vars(Y2011, Y2012),
             funs(n(), missing = sum(is.na(.)), mean(., na.rm = TRUE), median(.,na.rm = TRUE)))
#   Y2011_n Y2012_n Y2011_missing Y2012_missing Y2011_mean Y2012_mean Y2011_median Y2012_median
# 1      51      51             0             0    1574968    1591135      1575533      1643855

## How to apply Non-Standard Functions ------------------
# * Suppose you want to subtract mean from its original value and then calculate variance of it.
# * 假設要從原始值中減去平均值，然後計算其方差。

set.seed(222)
mydataF <- data.frame(X1=sample(1:100,100), X2=runif(100))
summarise_at(mydataF,vars(X1,X2), function(x) var(x - mean(x)))
#         X1         X2
# 1 841.6667 0.08142161


## Example 21 : Summarize all Numeric Variables ------------------
# * The summarise_if function allows you to summarise conditionally.
# * summarysif 函數可以讓您有條件地進行總結。

summarise_if(mydata, is.numeric, funs(n(),mean,median))
#   Y2002_n Y2003_n Y2004_n Y2005_n Y2006_n Y2007_n Y2008_n Y2009_n Y2010_n Y2011_n Y2012_n Y2013_n Y2014_n
# 1      51      51      51      51      51      51      51      51      51      51      51      51      51
#   Y2015_n Y2002_mean Y2003_mean Y2004_mean Y2005_mean Y2006_mean Y2007_mean Y2008_mean Y2009_mean
# 1      51    1566034    1509193    1540555    1522064    1530969    1553219    1538398    1658519
#   Y2010_mean Y2011_mean Y2012_mean Y2013_mean Y2014_mean Y2015_mean Y2002_median Y2003_median Y2004_median
# 1    1504108    1574968    1591135    1530078    1583360    1588297      1584734      1485909      1522230
#   Y2005_median Y2006_median Y2007_median Y2008_median Y2009_median Y2010_median Y2011_median Y2012_median
# 1      1480280      1531641      1563062      1545621      1658551      1498662      1575533      1643855
#   Y2013_median Y2014_median Y2015_median
# 1      1531212      1580394      1627508

# Alternative Method :
# First, store data for all the numeric variables
numdata = mydata[sapply(mydata,is.numeric)]
numdata

# Second, the summarise_all function calculates summary statistics for all the columns in a data frame
summarise_all(numdata, funs(n(),mean,median))


# Example 22 : Summarize Factor Variable ------------
# * We are checking the number of levels/categories and count of missing observations in a categorical (factor) variable.
# * 我們正在檢查分類（因子）變量中的級別/類別數量和缺失觀察次數。

# mydata = read.csv("data/sampledata.csv")
summarise_all(mydata["Index"], 
              funs(nlevels(.), sum(is.na(.))))
#   nlevels sum
# 1      19   0

# 原廠summarise {dplyr}	R Documentation 範例：
# * Reduces multiple values down to a single value
# * summarise() is typically used on grouped data created by group_by(). 
# * The output will have one row for each group.

#Examples
# A summary applied to ungrouped tbl returns a single row
mtcars %>%
    summarise(mean = mean(disp), n = n())

# Usually, you'll want to group first
mtcars %>%
    group_by(cyl) %>%
    summarise(mean = mean(disp), n = n())

# Each summary call removes one grouping level (since that group
# is now just a single row)
mtcars %>%
    group_by(cyl, vs) %>%
    summarise(cyl_n = n()) %>%
    group_vars()

# Note that with data frames, newly created summaries immediately
# overwrite existing variables
mtcars %>%
    group_by(cyl) %>%
    summarise(disp = mean(disp), sd = sd(disp))


# summarise() supports quasiquotation. You can unquote raw
# expressions or quosures:
var <- quo(mean(cyl))
summarise(mtcars, !! var)


# arrange() function :
# * Use : Sort data
# * Syntax
# * arrange(data_frame, variable(s)_to_sort)
# * or
# * data_frame %>% arrange(variable(s)_to_sort)
# * To sort a variable in descending order, use desc(x).

## Example 23 : 按多個變量排序數據 Sort Data by Multiple Variables -----------------
# * The default sorting order of arrange() function is ascending. 
# * In this example, we are sorting data by multiple variables.


head(arrange(mydata, Index, Y2011))
#   Index      State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010   Y2011   Y2012
# 1     A    Arizona 1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521 1130709 1907284
# 2     A     Alaska 1170302 1960378 1818085 1447852 1861639 1465841 1551826 1436541 1629616 1230866 1512804
# 3     A    Alabama 1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173 1237582 1440756 1186741
# 4     A   Arkansas 1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295 1928238 1216675
# 5     C California 1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809 1624509 1639670 1921845
# 6     C   Colorado 1343824 1878473 1886149 1236697 1871471 1814218 1875146 1752387 1913275 1665877 1491604

# Suppose you need to sort one variable by descending order and other variable by ascending oder.
head(arrange(mydata, desc(Index), Y2011))
#  Index         State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010   Y2011   Y2012
# 1    W    Washington 1977749 1687136 1199490 1163092 1334864 1621989 1545621 1555554 1179331 1150089 1775787
# 2    W West Virginia 1677347 1380662 1176100 1888948 1922085 1740826 1238174 1539322 1539603 1872519 1462137
# 3    W       Wyoming 1775190 1498098 1198212 1881688 1750527 1523124 1587602 1504455 1282142 1881814 1673668
# 4    W     Wisconsin 1788920 1518578 1289663 1436888 1251678 1721874 1980167 1901394 1648755 1940943 1729177
# 5    V      Virginia 1134317 1163996 1891068 1853855 1708715 1197698 1803330 1590043 1516758 1171686 1262342
# 6    V       Vermont 1146902 1832249 1492704 1579265 1332048 1563537 1123567 1618583 1326369 1792600 1714960

# # 原廠arrange {dplyr}	R Documentation 範例：
# * Arrange rows by variables
# * Description
# * Use desc() to sort a variable in descending 

# Examples

arrange(mtcars, cyl, disp)
arrange(mtcars, desc(disp))

# grouped arrange ignores groups
by_cyl <- mtcars %>% group_by(cyl)
by_cyl %>% arrange(desc(wt))
# Unless you specifically ask:
by_cyl %>% arrange(desc(wt), .by_group = TRUE)


# Pipe Operator 管道操作%>%
# * It is important to understand the pipe (%>%) operator before knowing the other functions of dplyr package. 
# * dplyr utilizes pipe operator from another package (magrittr).
# * It allows you to write sub-queries like we do it in sql.
# * Note : All the functions in dplyr package can be used without the pipe operator. 
# * The question arises "Why to use pipe operator %>%". 
# * The answer is it lets to wrap multiple functions together with the use of  %>%.
# * Syntax :
#     * filter(data_frame, variable == value)
# * or
# * data_frame %>% filter(variable == value)
# * The %>% is NOT restricted to filter function. It can be used with any function. 


#Example :
# The code below demonstrates the usage of pipe %>% operator. In this example, we are selecting 10 random observations of two variables "Index" "State" from the data frame "mydata".

(dt = sample_n(select(mydata, Index, State),5))
#    Index        State
# 18     K     Kentucky
# 31     N   New Jersey
# 39     P Pennsylvania
# 29     N       Nevada
# 17     K       Kansas
# or 
(dt = mydata %>% select(Index, State) %>% sample_n(5))
#    Index         State
# 4      A      Arkansas
# 50     W     Wisconsin
# 18     K      Kentucky
# 49     W West Virginia
# 33     N      New York

# group_by() function :
# * Use : Group data by categorical variable
# * Syntax :
#     * group_by(data, variables)
# * or
# * data %>% group_by(variables)

## Example 24 : Summarise Data by Categorical Variable ---------------
# * We are calculating count and mean of variables Y2011 and Y2012 by variable Index.
# * 我們通過變量Index計算變量Y2011和Y2012的計數和平均值。

t1 = summarise_at(group_by(mydata, Index), vars(Y2011, Y2012), funs(n(), mean(., na.rm = TRUE)))
t1
# The above code can also be written like
t2 = mydata %>% group_by(Index) %>%
    summarise_at(vars(Y2011,Y2012), funs(n(), mean(., na.rm = TRUE)))
t2

t3 = mydata %>% group_by(Index) %>%
    summarise_at(vars(Y2011:Y2015), funs(n(), mean(., na.rm = TRUE)))
t3


## do() function :
# * Use : Compute within groups
# * Syntax :
#     * do(data_frame, expressions_to_apply_to_each_group)
# * Note : The dot (.) is required to refer to a data frame.

## Example 25 : 過濾分類變量中的數據 Filter Data within a Categorical Variable ---------
# * Suppose you need to pull top 2 rows from 'A', 'C' and 'I' categories of variable Index. 


t = mydata %>% filter(Index %in% c("A", "C","I")) %>% group_by(Index) %>%
    do(head( . , 2))
t
# A tibble: 6 x 16
# Groups:   Index [3]
#   Index  State     Y2002   Y2003   Y2004  Y2005  Y2006  Y2007  Y2008  Y2009  Y2010  Y2011  Y2012  Y2013
#   <fctr> <fctr>    <int>   <int>   <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>
# 1 A      Alabama 1296530 1317711 1118631 1.49e6 1.11e6 1.44e6 1.95e6 1.94e6 1.24e6 1.44e6 1.19e6 1.85e6
# 2 A      Alaska  1170302 1960378 1818085 1.45e6 1.86e6 1.47e6 1.55e6 1.44e6 1.63e6 1.23e6 1.51e6 1.99e6
# 3 C      Califo~ 1685349 1675807 1889570 1.48e6 1.74e6 1.81e6 1.49e6 1.66e6 1.62e6 1.64e6 1.92e6 1.16e6
# 4 C      Colora~ 1343824 1878473 1886149 1.24e6 1.87e6 1.81e6 1.88e6 1.75e6 1.91e6 1.67e6 1.49e6 1.18e6
# 5 I      Idaho   1353210 1438538 1739154 1.54e6 1.12e6 1.77e6 1.34e6 1.75e6 1.44e6 1.46e6 1.64e6 1.31e6
# 6 I      Illino~ 1508356 1527440 1493029 1.26e6 1.54e6 1.75e6 1.87e6 1.66e6 1.42e6 1.75e6 1.70e6 1.92e6
# ... with 2 more variables: Y2014 <int>, Y2015 <int>

## Example 26 : 通過分類變量選擇第三最大值 Selecting 3rd Maximum Value by Categorical Variable ---------
# * We are calculating third maximum value of variable Y2015 by variable Index. 
# * The following code first selects only two variables Index and Y2015. 
# * Then it filters the variable Index with 'A', 'C' and 'I' and then it groups the same variable and sorts the variable Y2015 in descending order. 
# * At last, it selects the third row.
# * The slice() function is used to select rows by position.
# 
# * 我們通過變量Index計算變量Y2015的第三個最大值。
# * 以下代碼首先只選擇兩個變量Index和Y2015。
# * 然後使用'A'，'C'和'I'過濾變量Index，然後對同一個變量進行分組，並按照降序對變量Y2015進行排序。
# * 最後選擇第三行。
# * slice（）函數用於按位置選擇行。

t = mydata %>% select(Index, Y2015) %>%
    filter(Index %in% c("A", "C","I")) %>%
    group_by(Index) %>%
    do(arrange(.,desc(Y2015))) %>%  slice(3)  #slice（）函數用於按位置選擇行。
t
# The slice() function is used to select rows by position.


## Using Window Functions
# * Like SQL, dplyr uses window functions that are used to subset data within a group. 
# * It returns a vector of values. 
# * We could use min_rank() function that calculates rank in the preceding example,
# 
# * 像SQL一樣，dplyr使用用於在組中子集數據的窗口函數。
# * 返回值的向量。
# * 我們可以使用在前面的例子中計算rank的 min_rank（）函數，

t = mydata %>% select(Index, Y2015) %>%
    filter(Index %in% c("A", "C","I")) %>%
    group_by(Index) %>%
    filter(min_rank(desc(Y2015)) == 3)
t

## Example 27 : 總結，分組和排序 Summarize, Group and Sort Together  --------------
# * In this case, we are computing mean of variables Y2014 and Y2015 by variable Index. 
# * Then sort the result by calculated mean variable Y2015.
# 
# * 在這種情況下，我們是通過變量Index計算變量Y2014和Y2015的平均值。
# * 然後通過計算的平均變量Y2015對結果進行排序。


t = mydata %>%
    group_by(Index)%>%
    summarise(Mean_2014 = mean(Y2014, na.rm=TRUE),
              Mean_2015 = mean(Y2015, na.rm=TRUE)) %>%
    arrange(desc(Mean_2015))
t

# mutate() function :
# * Use : Creates new variables
# * Syntax :
#     * mutate(data_frame, expression(s) )
# * or
# * data_frame %>% mutate(expression(s))

## Example 28 : 創建一個新變量 Create a new variable --------------
# * The following code calculates division of Y2015 by Y2014 and name it "change".
# * 以下代碼按Y2014計算出Y2015的分數，並將其命名為“change”。

mydata1 = mutate(mydata, change=Y2015/Y2014)
head(mydata1)

## Example 29 : 將所有變量乘以1000 Multiply all the variables by 1000 --------------------
# * It creates new variables and name them with suffix "_new".
# * 它創建新變量，並使用後綴“_new”命名它們。

mydata11 = mutate_all(mydata, funs("new" = . * 1000))
head(mydata11)


mydata11Test = mutate_all(mydata, funs("new" = Y2006 * 1000))  ### ????
head(mydata11Test)

# 原廠 summarise_all {dplyr}	R Documentation 原廠 範例：
# * Summarise and mutate multiple columns.
# * summarise_all(), mutate_all() and transmute_all() 
# *    apply the functions to all (non-grouping) columns.
# * summarise_at(), mutate_at() and transmute_at() 
# *    allow you to select columns using the same name-based select_helpers just like with select().
# * summarise_if(), mutate_if() and transmute_if() 
# *    operate on columns for which a predicate returns TRUE.


#Examples
# The scoped variants of summarise() and mutate() make it easy to
# apply the same transformation to multiple variables:

iris %>%
    group_by(Species) %>%
    summarise_all(mean)

# There are three variants.
# * _all affects every variable
# * _at affects variables selected with a character vector or vars()
# * _if affects variables selected with a predicate function:

starwars %>% summarise_at(vars(height:mass), mean, na.rm = TRUE)
starwars %>% summarise_at(c("height", "mass"), mean, na.rm = TRUE)
starwars %>% summarise_if(is.numeric, mean, na.rm = TRUE)

# mutate_if is particularly useful for transforming variables from
# one type to another
iris %>% as_tibble() %>% mutate_if(is.factor, as.character)
iris %>% as_tibble() %>% mutate_if(is.double, as.integer)

# ---------------------------------------------------------------------------
# If you want apply multiple transformations, use funs()
by_species <- iris %>% group_by(Species)

by_species %>% summarise_all(funs(min, max))
# Note that output variable name now includes the function name, in order to
# keep things distinct.

# You can express more complex inline transformations using .
by_species %>% mutate_all(funs(. / 2.54))

# Function names will be included if .funs has names or multiple inputs
by_species %>% mutate_all(funs(cm = . / 2.54))
by_species %>% summarise_all(funs(med = median))
by_species %>% summarise_all(funs(Q3 = quantile), probs = 0.75)
by_species %>% summarise_all(c("min", "max"))


## Example 30 : 計算變量的排名 Calculate Rank for Variables --------------------
# * Suppose you need to calculate rank for variables Y2008 to Y2010.
# * 假設你需要計算變量Y2008到Y2010的等級。


mydata12 = mutate_at(mydata, vars(Y2008:Y2010), funs(Rank=min_rank(.)))
head(mydata12)

#  Index      State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008   Y2009   Y2010   Y2011   Y2012
# 1    A    Alabama 1296530 1317711 1118631 1492583 1107408 1440134 1945229 1944173 1237582 1440756 1186741
# 2    A     Alaska 1170302 1960378 1818085 1447852 1861639 1465841 1551826 1436541 1629616 1230866 1512804
# 3    A    Arizona 1742027 1968140 1377583 1782199 1102568 1109382 1752886 1554330 1300521 1130709 1907284
# 4    A   Arkansas 1485531 1994927 1119299 1947979 1669191 1801213 1188104 1628980 1669295 1928238 1216675
# 5    C California 1685349 1675807 1889570 1480280 1735069 1812546 1487315 1663809 1624509 1639670 1921845
# 6    C   Colorado 1343824 1878473 1886149 1236697 1871471 1814218 1875146 1752387 1913275 1665877 1491604
#     Y2013   Y2014   Y2015 Y2008_Rank Y2009_Rank Y2010_Rank
# 1 1852841 1558906 1916661         47         46          8
# 2 1985302 1580394 1979143         27          9         38
# 3 1363279 1525866 1647724         33         14         12
# 4 1591896 1360959 1329341          8         24         40
# 5 1156536 1388461 1644607         24         27         36
# 6 1178355 1383978 1330736         43         31         47

# By default, min_rank() assigns 1 to the smallest value and high number to the largest value. 
# In case, you need to assign rank 1 to the largest value of a variable, use min_rank(desc(.))
# 默認情況下，min_rank（）將最小值和最大值分配為1。
# 如果需要將rank 1分配給變量的最大值，請使用min_rank（desc（。））
mydata13 = mutate_at(mydata, vars(Y2008:Y2010), funs(Rank=min_rank(desc(.))))
head(mydata13)

# Example 31 : 選擇變量指數中收入最高的州 -----
#  Select State that generated highest income among the variable Index -----
# * 選擇在變量'Index'中生成最高收入的狀態


out = mydata %>% 
    group_by(Index) %>% 
    filter(min_rank(desc(Y2015)) == 1) %>%
    select(Index, Y2015, Y2008)
out
# A tibble: 19 x 3
# Groups:   Index [19]
#   Index    Y2015   Y2008
#   <fctr>   <int>   <int>
# 1 A      1979143 1551826
# 2 C      1718072 1764457
# 3 D      1627508 1762096
# 4 F      1170389 1756185
# 5 G      1725470 1773090

## Example 32 : “指數”的累積收益變量 Cumulative Income of 'Index' variable ----
# * The cumsum function calculates cumulative sum of a variable. 
# * With mutate function, we insert a new variable called 'Total' which contains values of cumulative income of variable Index.
# * cumsum函數計算變量的累積和。
# * 使用mutate函數，我們插入一個名為'Total'的新變量，其中包含變量Index的累積收入值。


out2 = mydata %>% 
    group_by(Index) %>% 
    mutate(Total=cumsum(Y2015)) %>%
    select(Index, Y2015, Total)
out2
# A tibble: 51 x 3
# Groups:   Index [19]
#   Index    Y2015   Total
#   <fctr>   <int>   <int>
# 1 A      1916661 1916661
# 2 A      1979143 3895804
# 3 A      1647724 5543528
# 4 A      1329341 6872869
# 5 C      1644607 1644607

# join() function :
#     
# Use : Join two datasets
# 
# Syntax :
# inner_join(x, y, by = )
# left_join(x, y, by = )
# right_join(x, y, by = )
# full_join(x, y, by = )
# semi_join(x, y, by = )
# anti_join(x, y, by = )
# x, y - datasets (or tables) to merge / join
# by - common variable (primary key) to join by.

### Example 33 : 內部聯接 兩個表共同有的列  Common rows in both the tables ----
df1 = data.frame(ID = c(1, 2, 3, 4, 5),
                 w = c('a', 'b', 'c', 'd', 'e'),
                 x = c(1, 1, 0, 0, 1),
                 y=rnorm(5),
                 z=letters[1:5])

df2 = data.frame(ID = c(1, 7, 3, 6, 8),
                 a = c('z', 'b', 'k', 'd', 'l'),
                 b = c(1, 2, 3, 0, 4),
                 c =rnorm(5),
                 d =letters[2:6])
# 內部聯接 INNER JOIN returns rows when there is a match in both tables. 
# In this example, we are merging df1 and df2 with ID as common variable (primary key). 

df1
#   ID w x           y z
# 1  1 a 1 -0.08531958 a  *
# 2  2 b 1 -0.64149639 b
# 3  3 c 0 -0.95547495 c  *
# 4  4 d 0 -0.99785644 d
# 5  5 e 1 -0.27101507 e
df2
#   ID a b          c d
# 1  1 z 1  0.4121976 b  *
# 2  7 b 2 -1.1095902 c
# 3  3 k 3 -0.6297584 d  *
# 4  6 d 0  0.3494119 e
# 5  8 l 4 -0.4627422 f

# 內部聯接 >>  只選共有的 ID 內部聯接
df3 = inner_join(df1, df2, by = "ID")
df3
#   ID w x           y z a b          c d
# 1  1 a 1 -0.08531958 a z 1  0.4121976 b
# 2  3 c 0 -0.95547495 c k 3 -0.6297584 d

###　Example 34 :  左聯接　Applying LEFT JOIN　----

# LEFT JOIN：即使右表中沒有匹配，它也會返回左表中的所有行。 >>> NA
# LEFT JOIN : It returns all rows from the left table, even if there are no matches in the right table. 

left_join(df1, df2, by = "ID")
# 　ID w x           y z    a  b          c    d
# 1  1 a 1 -0.08531958 a    z  1  0.4121976    b
# 2  2 b 1 -0.64149639 b <NA> NA         NA <NA>
# 3  3 c 0 -0.95547495 c    k  3 -0.6297584    d
# 4  4 d 0 -0.99785644 d <NA> NA         NA <NA>
# 5  5 e 1 -0.27101507 e <NA> NA         NA <NA>

# 垂直合併數據　Combine Data Vertically
# 
# intersect(x, y)
# Rows that appear in both x and y. 行x和y都出現。
# 
# union(x, y)
# Rows that appear in either or both x and y.
# 
# setdiff(x, y)
# Rows that appear in x but not y.

### Example 35 : Applying INTERSECT -----

# Prepare Sample Data for Demonstration
mtcars
#                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
# Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
# Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
# Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
# Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
# Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
# Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1

dim(mtcars) # [1] 32 11

mtcars$model <- rownames(mtcars)
mtcars
#                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb               model
# Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4           Mazda RX4
# Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4       Mazda RX4 Wag
# Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1          Datsun 710
# Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1      Hornet 4 Drive
# Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2   Hornet Sportabout

first <- mtcars[1:20, ]
first
dim(first)  # [1] 20 12
second <- mtcars[10:nrow(mtcars), ]
second
dim(second)  # [1] 23 12

# 行x和y都出現。
# INTERSECT selects unique rows that are common to both the data frames.選擇對這兩個數據幀通用的唯一行。
intersect12 <- intersect(first, second)
dim(intersect12)  # [1] 11 12
intersect12
#     mpg cyl  disp  hp drat    wt  qsec vs am gear carb               model
# 1  19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4            Merc 280
# 2  17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4           Merc 280C
# 3  16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3          Merc 450SE
# 4  17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3          Merc 450SL
# 5  15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3         Merc 450SLC
# 6  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4  Cadillac Fleetwood
# 7  10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4 Lincoln Continental
# 8  14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4   Chrysler Imperial
# 9  32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1            Fiat 128
# 10 30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2         Honda Civic
# 11 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1      Toyota Corolla

### Example 36 : Applying UNION ----

# UNION顯示來自兩個表格的所有行，並從組合數據集中刪除重複的記錄。
# 通過使用union_all函數，它允許組合數據集中的重複行。
# UNION displays all rows from both the tables and removes duplicate records from the combined dataset. 
# By using union_all function, it allows duplicate rows in the combined dataset.

x=data.frame(ID = 1:6, ID1= 1:6)
y=data.frame(ID = 1:6,  ID1 = 1:6)
x
y
union(x,y)
union_all(x,y)

### Example 37 : 行出現在一個表中，但不出現在其他表中 Rows appear in one table but not in other table ----

setdiff(first, second)
#    mpg cyl  disp  hp drat    wt  qsec vs am gear carb             model
# 1 21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4         Mazda RX4
# 2 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4     Mazda RX4 Wag
# 3 22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1        Datsun 710
# 4 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1    Hornet 4 Drive
# 5 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2 Hornet Sportabout
# 6 18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1           Valiant
# 7 14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4        Duster 360
# 8 24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2         Merc 240D
# 9 22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2          Merc 230


# Example 38 : IF ELSE Statement 非常好用-------
# 
# Syntax :
#     if_else(condition, true, false, missing = NULL)
# true  : Value if condition meets
# false : Value if condition does not meet
# missing : Value if missing cases.It will be used to replace missing values (Default : NULL)
df <- c(-10,2, NA)
df
# [1] -10   2  NA

if_else(df < 0, "negative", "positive", missing = "missing value")

# Create a new variable with IF_ELSE
# If a value is less than 5, add it to 1 and if it is greater than or equal to 5, add it to 2. Otherwise 0.

df =　data.frame(x = c(1,5,6,NA))
df
#    x
# 1  1
# 2  5
# 3  6
# 4 NA

df %>% mutate(newvar=if_else(x<5, x+1, x+2,0))
#    x newvar
# 1  1      2  +1
# 2  5      7  +2
# 3  6      8  +2
# 4 NA      0   0

?if_else   #Vectorised if

# Nested IF ELSE

# Multiple IF ELSE statement can be written using if_else() function. See the example below -
mydf =data.frame(x = c(1:5,NA))
mydf
#    x
# 1  1
# 2  2
# 3  3
# 4  4
# 5  5
# 6 NA
mydf %>% mutate(newvar= if_else(is.na(x),"I am missing",
                                if_else(x==1,"I am one",
                                if_else(x==2,"I am two",
                                if_else(x==3,"I am three","Others")))))
#    x       newvar
# 1  1     I am one
# 2  2     I am two
# 3  3   I am three
# 4  4       Others
# 5  5       Others
# 6 NA I am missing

# SQL-Style CASE WHEN Statement
# We can use case_when() function to write nested if-else queries. 
# In case_when(), you can use variables directly within case_when() wrapper. TRUE refers to ELSE statement. 
mydf %>% mutate(flag = case_when(is.na(x) ~ "I am missing",
                                 x == 1 ~ "I am one",
                                 x == 2 ~ "I am two",
                                 x == 3 ~ "I am three",
                                 TRUE ~ "Others"))
#    x         flag
# 1  1     I am one
# 2  2     I am two
# 3  3   I am three
# 4  4       Others
# 5  5       Others
# 6 NA I am missing
 
# Important Point
# Make sure you set is.na() condition at the beginning in nested ifelse. Otherwise, it would not be executed.

### Example 39 :  Apply ROW WISE 明智的 Operation  -----

# 假設您想在2012年，2013年，2014年，2015年的每一行變量中找到最大值。
# Suppose you want to find maximum value in each row of variables 2012, 2013, 2014, 2015. 
# The rowwise() function allows you to apply functions to rows.
df = mydata %>%
    rowwise() %>% mutate(Max= max(Y2012:Y2015)) %>%
    select(Y2012:Y2015,Max)
df
# Source: local data frame [51 x 5]
# Groups: <by row>
#     
#     # A tibble: 51 x 5
#     Y2012   Y2013   Y2014   Y2015     Max
#     <int>   <int>   <int>   <int>   <int>
# 1 1186741 1852841 1558906 1916661 1916661
# 2 1512804 1985302 1580394 1979143 1979143
# 3 1907284 1363279 1525866 1647724 1907284
# 4 1216675 1591896 1360959 1329341 1329341


### Example 40 : Combine Data Frames ---

# Suppose you are asked to combine two data frames. Let's first create two sample datasets.
df1=data.frame(ID = 1:6,  x=letters[1:6])
df2=data.frame(ID = 7:12, x=letters[7:12])
df1
#   ID x
# 1  1 a
# 2  2 b
# 3  3 c
# 4  4 d
# 5  5 e
# 6  6 f
df2
#   ID x
# 1  7 g
# 2  8 h
# 3  9 i
# 4 10 j
# 5 11 k
# 6 12 l

# The bind_rows() function combine two datasets with rows. 
# So combined dataset would contain 12 rows (6+6) and 2 columns.

xy = bind_rows(df1,df2)
xy
#    ID x
# 1   1 a
# 2   2 b
# 3   3 c
# 4   4 d
# 5   5 e
# 6   6 f
# 7   7 g
# 8   8 h
# 9   9 i
# 10 10 j
# 11 11 k
# 12 12 l

# It is equivalent to base R function rbind.

xy = rbind(df1,df2)
xy
# The bind_cols() function combine two datasets with columns. 
# So combined dataset would contain 4 columns and 6 rows.
xyC = bind_cols(df1,df2)
xyC
#   ID x ID1 x1
# 1  1 a   7  g
# 2  2 b   8  h
# 3  3 c   9  i
# 4  4 d  10  j
# 5  5 e  11  k
# 6  6 f  12  l
# or
xyCbind = cbind(df1,df2)      # The output is shown below-
xyCbind

### Example 41 : 計算百分比值 Calculate Percentile Values ----

# The quantile() function is used to determine Nth percentile value. 
# In this example, we are computing percentile values by variable Index.

mydata %>% group_by(Index) %>%
    summarise(Pecentile_25=quantile(Y2015, probs=0.25),
              Pecentile_50=quantile(Y2015, probs=0.5),
              Pecentile_75=quantile(Y2015, probs=0.75),
              Pecentile_99=quantile(Y2015, probs=0.99))

# A tibble: 19 x 5
#   Index  Pecentile_25 Pecentile_50 Pecentile_75 Pecentile_99
#   <fctr>        <dbl>        <dbl>        <dbl>        <dbl>
# 1 A           1568128      1782192      1932282      1977269
# 2 C           1487672      1644607      1681340      1716603
# 3 D           1464514      1518846      1573177      1625335
# 4 F           1170389      1170389      1170389      1170389
# 5 G           1725470      1725470      1725470      1725470

# The ntile() function is used to divide the data into N bins.

x= data.frame(N= 1:10)
x
x = mutate(x, pos = ntile(x$N,5))
x
#     N pos
# 1   1   1
# 2   2   1
# 3   3   2
# 4   4   2
# 5   5   3
# 6   6   3
# 7   7   4
# 8   8   4
# 9   9   5
# 10 10   5

### Example 42 : Automate Model Building  -----

# This example explains the advanced usage of do() function. 
# In this example, we are building linear regression model for each level of a categorical variable. 
# There are 3 levels in variable cyl of dataset mtcars.

length(unique(mtcars$cyl))
# [1] 3

by_cyl <- group_by(mtcars, cyl)
by_cyl
# A tibble: 32 x 12
# Groups:   cyl [3]
#     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb model            
# * <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>            
# 1  21.0  6.00   160 110    3.90  2.62  16.5  0     1.00  4.00  4.00 Mazda RX4        
# 2  21.0  6.00   160 110    3.90  2.88  17.0  0     1.00  4.00  4.00 Mazda RX4 Wag    
# 3  22.8  4.00   108  93.0  3.85  2.32  18.6  1.00  1.00  4.00  1.00 Datsun 710       
# 4  21.4  6.00   258 110    3.08  3.22  19.4  1.00  0     3.00  1.00 Hornet 4 Drive   
# 5  18.7  8.00   360 175    3.15  3.44  17.0  0     0     3.00  2.00 Hornet Sportabout
# 6  18.1  6.00   225 105    2.76  3.46  20.2  1.00  0     3.00  1.00 Valiant  

models <- by_cyl %>% do(mod = lm(mpg ~ disp, data = .))

summarise(models, rsq = summary(mod)$r.squared)
     models %>% do(data.frame(
    var = names(coef(.$mod)),
    coef(summary(.$mod)))
)
     # A tibble: 3 x 1
     # rsq
     # <dbl>
     # 1 0.648 
     # 2 0.0106
     # 3 0.270
         
# if() Family of Functions
     
#It includes functions like select_if, mutate_if, summarise_if. 
# They come into action only when logical condition meets. See examples below.
     
### Example 43 : Select only numeric columns ----
     
# The select_if() function returns only those columns where logical condition is TRUE. 
# The is.numeric refers to retain only numeric variables.
     
mydata2 = select_if(mydata, is.numeric)
mydata2
# Similarly, you can use the following code for selecting factor columns - 
mydata3 = select_if(mydata, is.factor)
mydata3     
     
### Example 44 : Number of levels in factor variables -----
 
# Like select_if() function, summarise_if() function lets you to summarise only for variables where logical condition holds.

summarise_if(mydata, is.factor, funs(nlevels(.)))
#   Index State
# 1    19    51

# It returns 19 levels for variable Index and 51 levels for variable State.

### Example 45 : Multiply by 1000 to numeric variables -----
mydata11 = mutate_if(mydata, is.numeric, funs("new" = .* 1000))
mydata11


### Example 46 : Convert value to NA ------

# In this example, we are converting "" to NA using na_if() function.
k <- c("a", "b", "", "d")
k
# [1] "a" "b" ""  "d"
na_if(k, "")
# [1] "a" "b" NA  "d"

### 練習01: 請將資料集 Year 年欄位由大到小-----
mydata3 = select(mydata, starts_with("Y"))
Years <- names(select(mydata, starts_with("Y")))

# R中排序:sort()，rank()，order() 
?sort
order(Years)
sort(Years)
sort(Years, decreasing = TRUE)
rank(Years)

YearsDecreasing <- sort(Years, decreasing = TRUE)
mydataYearsDecreasing = select(mydata, YearsDecreasing, everything())
mydataYearsDecreasing2 = select(mydata, YearsDecreasing)
mydataYearsDecreasing3 = select(mydata, Index, State,YearsDecreasing)

### 練習02: 請將mydata 資料集新增region 區域欄位-----

?state    # US State Facts and Figures
state.name
# [1] "Alabama"        "Alaska"         "Arizona"        "Arkansas"       "California"     "Colorado"      
# [7] "Connecticut"    "Delaware"       "Florida"        "Georgia"        "Hawaii"         "Idaho"         
# [13] "Illinois"       "Indiana"        "Iowa"           "Kansas"         "Kentucky"       "Louisiana"     
# [19] "Maine"          "Maryland"       "Massachusetts"  "Michigan"       "Minnesota"      "Mississippi"   
# [25] "Missouri"       "Montana"        "Nebraska"       "Nevada"         "New Hampshire"  "New Jersey"    
# [31] "New Mexico"     "New York"       "North Carolina" "North Dakota"   "Ohio"           "Oklahoma"      
# [37] "Oregon"         "Pennsylvania"   "Rhode Island"   "South Carolina" "South Dakota"   "Tennessee"     
# [43] "Texas"          "Utah"           "Vermont"        "Virginia"       "Washington"     "West Virginia" 
# [49] "Wisconsin"      "Wyoming" 

state.region
# [1] South         West          West          South         West          West          Northeast    
# [8] South         South         South         West          West          North Central North Central
# [15] North Central North Central South         South         Northeast     South         Northeast    
# [22] North Central North Central South         North Central West          North Central West         
# [29] Northeast     Northeast     West          Northeast     South         North Central North Central
# [36] South         West          Northeast     Northeast     South         North Central South        
# [43] South         West          Northeast     South         West          South         North Central
# [50] West         
# Levels: Northeast South North Central West

mydata$State
# [1] Alabama              Alaska               Arizona              Arkansas             California          
# [6] Colorado             Connecticut          Delaware             District of Columbia Florida             
# [11] Georgia              Hawaii               Idaho                Illinois             Indiana             
# [16] Iowa                 Kansas               Kentucky             Louisiana            Maine               
# [21] Maryland             Massachusetts        Michigan             Minnesota            Mississippi         
# [26] Missouri             Montana              Nebraska             Nevada               New Hampshire       
# [31] New Jersey           New Mexico           New York             North Carolina       North Dakota        
# [36] Ohio                 Oklahoma             Oregon               Pennsylvania         Rhode Island        
# [41] South Carolina       South Dakota         Tennessee            Texas                Utah                
# [46] Vermont              Virginia             Washington           West Virginia        Wisconsin           
# [51] Wyoming             
# 51 Levels: Alabama Alaska Arizona Arkansas California Colorado Connecticut Delaware ... Wyoming

# [R] Appending new values to an existing factor vector
Region51 <- state.region[1:8]
Region51
class(Region51)
which(state.name == "Maryland")  # [1] 20

Region51 <- factor(append(as.character(Region51),as.character(state.region[20])))
Region51

Region51 <- factor(append(as.character(Region51),as.character(state.region[9:50])))
Region51

# Region51 <- factor(c(Region51, state.region[20]))
# Region51

mydata51 <- cbind(mydata, Region51)
mydata51

mydata51 = select(mydata51, State, Region51, everything())
mydata51

### 作業 01 ---

# 請完成以下網頁所有 練習
# # http://zjdian.com/2014/10/17/2014-10-17-dplyr/

install.packages("hflights")
library(hflights)
#explore data
data(hflights)
head(hflights,3)
dim(hflights)
# [1] 227496     21

?hflights
#1. 請說明 hflights 資料集 21 個變數的中文名稱與意義?
#年 月 日 禮拜幾 離開時間 到達時間 當前位置 飛機航號 航線 經過時間 航行時間 延誤時間 起飛前延誤時間 起飛機場 降落機場 飛行距離 起飛跑道 落地跑道 取消 取消至哪

#2. 我想知道某月，某天的航班？
filter(hflights, Month == 1,DayofMonth == 1)
### 補充講義 -------------------
# http://zjdian.com/2014/10/17/2014-10-17-dplyr/

